name: stan

on:
  push:
  pull_request:

jobs:
  build:
    name: ghc-${{ matrix.ghc }} z3-4.10.2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "8.10.7"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Workaround runner image issue
        # https://github.com/actions/runner-images/issues/7061
        run: sudo chown -R $USER /usr/local/.ghcup

      - uses: haskell/actions/setup@v1
        name: Setup GHC and cabal-install
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v2
        name: cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - uses: pavpanchekha/setup-z3@6b2d476d7a9227e0d8d2b94f73cd9fcba91b5e98
        name: setup z3
        with:
          version: "4.10.2"

      - name: update
        run: cabal update

      - name: install stan
        run: cabal install stan --installdir=.bin --install-method=copy --overwrite-policy=always

      - name: generate .hie for analysis
        run: cabal build liquid-fixpoint:lib:liquid-fixpoint

      - name: stan
        run: .bin/stan report
